FROM debian

ADD debian.list /etc/apt/sources.list.d/


RUN apt-get update && apt-get -y upgrade && apt -y install nginx && apt-get clean && \
    cd /var/www/ && rm -rf ./* && \
    mkdir -p Apelsin.com/img && \
    chmod -R 754 /var/www/Apelsin.com/ && \
    useradd Aleksandr && groupadd Nazarov && usermod -a -G Nazarov Aleksandr && \
    chown -R Aleksandr:Nazarov /var/www/Apelsin.com && \
    sed -i 's$/var/www/html$/var/www/Apelsin.com$g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user Aleksandr/g' /etc/nginx/nginx.conf
	
ADD index.html /var/www/Apelsin.com/
ADD img.jpg /var/www/Apelsin.com/img/
CMD ["nginx", "-g", "daemon off;"]
