FROM debian
WORKDIR /var/www/IskatelApelsina.com

ADD debian.list /etc/apt/sources.list.d/

RUN apt-get -qq update && \
    apt-get autoclean && \
    apt-get install -y nginx && \
    rm -rf /var/www/* && \
    mkdir /var/www/IskatelApelsina.com && \
    mkdir /var/www/IskatelApelsina.com/img 

COPY index.html /var/www/IskatelApelsina.com

COPY img.jpg /var/IskatelApelsina.com/img

RUN chmod -R 754 /var/www/IskatelApelsina.com && \
    useradd Aleksandr && \
    groupadd Nazarov && \
    usermod -aG Nazarov Aleksandr && \
    chown -R Aleksandr:Nazarov /var/www/IskatelApelsina.com

RUN sed -i 's/html/IskatelApelsina.com/g' /etc/nginx/sites-enabled/default && \
    sed -i 's/www-data/Aleksandr/g' /etc/nginx/nginx.conf && \
    sed -i 's/index.htm/index.html/g' /etc/nginx/sites-enabled/default

CMD ["nginx","-g","daemon off;"]
